### ISSUE TITLE
Use text-utils to fix broken CSV files

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-dash#81]
Use the `text-file-utils` to improve the success of CSV imports
More info : https://github.com/akvo/akvo-commons/issues/24

**Comment by jonase** [comment]
* The latest release of https://github.com/clojure/data.csv resolved some of the line ending problems we saw. Check the added tests for commit https://github.com/clojure/data.csv/commit/2a4b8a365b1a3dabe4c9b5455c2b33523fcef559
* With that in mind all we need is a reader created via [Tika.parse](https://tika.apache.org/1.2/api/org/apache/tika/Tika.html#parse(java.io.InputStream))

so instead of (from the data.csv readme)
```
(with-open [in-file (io/reader "in-file.csv")]
  (doall
    (csv/read-csv in-file)))
```
we can do
```
(with-open [input-stream (io/input-stream "in-file.csv")
            reader (io/reader (.parse (Tika.) input-stream))
  (doall 
    (csv/read-csv reader)))
```
to get the same "semantics" as in [text-file-utils](https://github.com/akvo/akvo-flow-services/blob/develop/src/akvo/flow_services/text_file_utils.clj#L21).

Note that text-file-utils is `file-in -> file-out` which might not be what we want if we just want to read the content (either from a url or a file on disk) and stream the result to a pg table.

**Comment by iperdomo** [comment]
@jonase OK, thanks for the clarification. I'll keep the issue open so we remember to use your approach instead of text-file-utils

**Comment by iperdomo** [comment]
We're not using `data.csv` to import a text file to the database
